// Generated by wxt
export {}
declare global {
  const AADHAAR_REGEX: typeof import('C:/sih/171/extension/src/utils/piiNormalizer')['AADHAAR_REGEX']
  const ADDRESS_COMPONENT_THRESHOLD: typeof import('C:/sih/171/extension/src/utils/addressDetector')['ADDRESS_COMPONENT_THRESHOLD']
  const ADDRESS_PATTERNS: typeof import('C:/sih/171/extension/src/utils/addressDetector')['ADDRESS_PATTERNS']
  const ADDRESS_REDACTED: typeof import('C:/sih/171/extension/src/utils/addressDetector')['ADDRESS_REDACTED']
  const ADDRESS_SCORE_THRESHOLD: typeof import('C:/sih/171/extension/src/utils/addressDetector')['ADDRESS_SCORE_THRESHOLD']
  const CARD_REGEX: typeof import('C:/sih/171/extension/src/utils/piiNormalizer')['CARD_REGEX']
  const CLASSIFIED_MARKING_REGEX: typeof import('C:/sih/171/extension/src/utils/piiNormalizer')['CLASSIFIED_MARKING_REGEX']
  const CLASS_NAMES: typeof import('C:/sih/171/extension/src/utils/onnxEngine')['CLASS_NAMES']
  const ContentScriptContext: typeof import('wxt/client')['ContentScriptContext']
  const GEOSPATIAL_COORD_REGEX: typeof import('C:/sih/171/extension/src/utils/piiNormalizer')['GEOSPATIAL_COORD_REGEX']
  const InvalidMatchPattern: typeof import('wxt/sandbox')['InvalidMatchPattern']
  const LOCATION_REDACTED: typeof import('C:/sih/171/extension/src/utils/addressDetector')['LOCATION_REDACTED']
  const MASKED_AADHAAR_REGEX: typeof import('C:/sih/171/extension/src/utils/piiNormalizer')['MASKED_AADHAAR_REGEX']
  const MatchPattern: typeof import('wxt/sandbox')['MatchPattern']
  const MigrationError: typeof import('wxt/storage')['MigrationError']
  const PAN_REGEX: typeof import('C:/sih/171/extension/src/utils/piiNormalizer')['PAN_REGEX']
  const PASSPORT_REGEX: typeof import('C:/sih/171/extension/src/utils/piiNormalizer')['PASSPORT_REGEX']
  const PHONE_REGEX: typeof import('C:/sih/171/extension/src/utils/piiNormalizer')['PHONE_REGEX']
  const PaddleAdapter: typeof import('C:/sih/171/extension/src/utils/ocrEngine')['PaddleAdapter']
  const SAFE_TOKENS: typeof import('C:/sih/171/extension/src/utils/leakVerifier')['SAFE_TOKENS']
  const SessionLogger: typeof import('C:/sih/171/extension/src/utils/sessionLogger')['SessionLogger']
  const SovereignOcrAdapter: typeof import('C:/sih/171/extension/src/utils/ocrEngine')['SovereignOcrAdapter']
  const ThemeToggle: typeof import('C:/sih/171/extension/src/components/ThemeToggle')['ThemeToggle']
  const VERIFICATION_PII_PATTERNS: typeof import('C:/sih/171/extension/src/utils/leakVerifier')['VERIFICATION_PII_PATTERNS']
  const analyzeAddressText: typeof import('C:/sih/171/extension/src/utils/addressDetector')['analyzeAddressText']
  const applyTheme: typeof import('C:/sih/171/extension/src/utils/theme')['applyTheme']
  const binarize: typeof import('C:/sih/171/extension/src/utils/dbPostProcess')['binarize']
  const browser: typeof import('wxt/browser')['browser']
  const canFetchExtensionAssets: typeof import('C:/sih/171/extension/src/utils/ocrEngine')['canFetchExtensionAssets']
  const checkModelAvailability: typeof import('C:/sih/171/extension/src/utils/onnxEngine')['checkModelAvailability']
  const checkOcrAvailability: typeof import('C:/sih/171/extension/src/utils/ocrEngine')['checkOcrAvailability']
  const classifyHardwareTier: typeof import('C:/sih/171/extension/src/utils/hardwareTier')['classifyHardwareTier']
  const computeIoU: typeof import('C:/sih/171/extension/src/utils/nms')['computeIoU']
  const connectedComponents: typeof import('C:/sih/171/extension/src/utils/dbPostProcess')['connectedComponents']
  const containsFullAddress: typeof import('C:/sih/171/extension/src/utils/addressDetector')['containsFullAddress']
  const createIframeUi: typeof import('wxt/client')['createIframeUi']
  const createIntegratedUi: typeof import('wxt/client')['createIntegratedUi']
  const createShadowRootUi: typeof import('wxt/client')['createShadowRootUi']
  const ctcDecodeWithDict: typeof import('C:/sih/171/extension/src/utils/ctc')['ctcDecodeWithDict']
  const ctcGreedyDecode: typeof import('C:/sih/171/extension/src/utils/ctc')['ctcGreedyDecode']
  const dbPostProcess: typeof import('C:/sih/171/extension/src/utils/dbPostProcess')['dbPostProcess']
  const defineAppConfig: typeof import('wxt/sandbox')['defineAppConfig']
  const defineBackground: typeof import('wxt/sandbox')['defineBackground']
  const defineConfig: typeof import('wxt')['defineConfig']
  const defineContentScript: typeof import('wxt/sandbox')['defineContentScript']
  const defineUnlistedScript: typeof import('wxt/sandbox')['defineUnlistedScript']
  const defineWxtPlugin: typeof import('wxt/sandbox')['defineWxtPlugin']
  const detectAddresses: typeof import('C:/sih/171/extension/src/utils/addressDetector')['detectAddresses']
  const detectHardwareTier: typeof import('C:/sih/171/extension/src/utils/hardwareTier')['detectHardwareTier']
  const detectUIElements: typeof import('C:/sih/171/extension/src/utils/onnxEngine')['detectUIElements']
  const evaluateTextPII: typeof import('C:/sih/171/extension/src/utils/piiNormalizer')['evaluateTextPII']
  const extractAddressComponents: typeof import('C:/sih/171/extension/src/utils/addressDetector')['extractAddressComponents']
  const extractCityAndPin: typeof import('C:/sih/171/extension/src/utils/addressDetector')['extractCityAndPin']
  const fakeBrowser: typeof import('wxt/testing')['fakeBrowser']
  const generateSessionId: typeof import('C:/sih/171/extension/src/utils/sessionLogger')['generateSessionId']
  const getHardwareProfile: typeof import('C:/sih/171/extension/src/utils/hardwareTier')['getHardwareProfile']
  const getInitialTheme: typeof import('C:/sih/171/extension/src/utils/theme')['getInitialTheme']
  const getOcrStatus: typeof import('C:/sih/171/extension/src/utils/ocrEngine')['getOcrStatus']
  const getUIStatus: typeof import('C:/sih/171/extension/src/utils/onnxEngine')['getUIStatus']
  const imageDataToNCHW: typeof import('C:/sih/171/extension/src/utils/tensor')['imageDataToNCHW']
  const injectScript: typeof import('wxt/client')['injectScript']
  const isIdCardGeometry: typeof import('C:/sih/171/extension/src/utils/piiNormalizer')['isIdCardGeometry']
  const isLuhnValid: typeof import('C:/sih/171/extension/src/utils/leakVerifier')['isLuhnValid']
  const isOcrAvailable: typeof import('C:/sih/171/extension/src/utils/ocrEngine')['isOcrAvailable']
  const isRestrictedUrl: typeof import('C:/sih/171/extension/src/utils/urlHelper')['isRestrictedUrl']
  const isVerticallyAdjacent: typeof import('C:/sih/171/extension/src/utils/addressDetector')['isVerticallyAdjacent']
  const isWasmSupported: typeof import('C:/sih/171/extension/src/utils/ocrEngine')['isWasmSupported']
  const loadOcrDict: typeof import('C:/sih/171/extension/src/utils/ctc')['loadOcrDict']
  const maskAddress: typeof import('C:/sih/171/extension/src/utils/addressDetector')['maskAddress']
  const nms: typeof import('C:/sih/171/extension/src/utils/nms')['nms']
  const normalizeCoordinatesConfusion: typeof import('C:/sih/171/extension/src/utils/piiNormalizer')['normalizeCoordinatesConfusion']
  const normalizeNumericConfusion: typeof import('C:/sih/171/extension/src/utils/piiNormalizer')['normalizeNumericConfusion']
  const normalizePanConfusion: typeof import('C:/sih/171/extension/src/utils/piiNormalizer')['normalizePanConfusion']
  const ocrDetect: typeof import('C:/sih/171/extension/src/utils/ocrEngine')['ocrDetect']
  const ocrRecognize: typeof import('C:/sih/171/extension/src/utils/ocrEngine')['ocrRecognize']
  const parseOcrDict: typeof import('C:/sih/171/extension/src/utils/ctc')['parseOcrDict']
  const postprocess: typeof import('C:/sih/171/extension/src/utils/onnxEngine')['postprocess']
  const preprocess: typeof import('C:/sih/171/extension/src/utils/onnxEngine')['preprocess']
  const runSecurityBoundaryVerification: typeof import('C:/sih/171/extension/src/utils/leakVerifier')['runSecurityBoundaryVerification']
  const scoreComponents: typeof import('C:/sih/171/extension/src/utils/addressDetector')['scoreComponents']
  const sessionLogger: typeof import('C:/sih/171/extension/src/utils/sessionLogger')['default']
  const shouldFailClosedQuarantine: typeof import('C:/sih/171/extension/src/utils/piiNormalizer')['shouldFailClosedQuarantine']
  const storage: typeof import('wxt/storage')['storage']
  const stripOwnMasks: typeof import('C:/sih/171/extension/src/utils/leakVerifier')['stripOwnMasks']
  const unionBbox: typeof import('C:/sih/171/extension/src/utils/addressDetector')['unionBbox']
  const useAppConfig: typeof import('wxt/client')['useAppConfig']
  const useTheme: typeof import('C:/sih/171/extension/src/utils/theme')['useTheme']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { AddressComponent, AddressMaskMode, SanitizedElement, AddressTextAnalysis, AddressDetection, AddressSensitiveRegion, AddressDetectionResult } from 'C:/sih/171/extension/src/utils/addressDetector'
  import('C:/sih/171/extension/src/utils/addressDetector')
  // @ts-ignore
  export type { Quad } from 'C:/sih/171/extension/src/utils/dbPostProcess'
  import('C:/sih/171/extension/src/utils/dbPostProcess')
  // @ts-ignore
  export type { HardwareTier, HardwareProfile } from 'C:/sih/171/extension/src/utils/hardwareTier'
  import('C:/sih/171/extension/src/utils/hardwareTier')
  // @ts-ignore
  export type { SensitiveRegion, RedactedRegion, SanitizedDomElement, VerificationResult } from 'C:/sih/171/extension/src/utils/leakVerifier'
  import('C:/sih/171/extension/src/utils/leakVerifier')
  // @ts-ignore
  export type { PaddleAdapter, OcrQuad, OcrRecognition, OcrAdapter } from 'C:/sih/171/extension/src/utils/ocrEngine'
  import('C:/sih/171/extension/src/utils/ocrEngine')
  // @ts-ignore
  export type { UIElement } from 'C:/sih/171/extension/src/utils/onnxEngine'
  import('C:/sih/171/extension/src/utils/onnxEngine')
  // @ts-ignore
  export type { SessionLogger, AgentSession } from 'C:/sih/171/extension/src/utils/sessionLogger'
  import('C:/sih/171/extension/src/utils/sessionLogger')
  // @ts-ignore
  export type { Theme } from 'C:/sih/171/extension/src/utils/theme'
  import('C:/sih/171/extension/src/utils/theme')
}
